#!/usr/bin/env python3
"""
Security Trinity - TheHive & Cortex Integration
Creates real alerts, cases, and runs analyzers
"""

from thehive4py.api import TheHiveApi
from thehive4py.models import Alert, Case, CaseObservable
from cortex4py.api import Api as CortexApi
import requests
import json
import uuid
from datetime import datetime

# ============================================
# CONFIGURATION
# ============================================

THEHIVE_URL = "http://localhost:9000"
THEHIVE_API_KEY = "4lhBlNvV6lgDcUiKHj+FHpfI7Ozu/SYl"  # Replace with your key

CORTEX_URL = "http://localhost:9001"
CORTEX_API_KEY = "oYMPnNSpR/Mz3i83uNuOhgIhTywimHSx"    # Replace with your key

# ============================================
# INITIALIZE CONNECTIONS
# ============================================

thehive = TheHiveApi(THEHIVE_URL, THEHIVE_API_KEY)
cortex = CortexApi(CORTEX_URL, CORTEX_API_KEY)

print("🔌 Security Trinity Integration Starting...")
print(f"✅ TheHive connected: {THEHIVE_URL}")
print(f"✅ Cortex connected: {CORTEX_URL}")

# ============================================
# FUNCTION 1: Create Alert from Coral Data
# ============================================

def create_alert_from_coral(github_user, slack_channel, sentry_project, severity=2):
    """Create an alert in TheHive based on Coral query results"""
    
    source_ref = f"coral-{uuid.uuid4().hex[:8]}"
    
    alert = Alert(
        title=f"[Security Trinity] Suspicious Activity from {github_user}",
        description=f"""
Coral cross-source investigation detected activity:

📊 GitHub User: {github_user}
💬 Slack Channel: {slack_channel}
⚠️ Sentry Project: {sentry_project}

This alert was auto-generated by the Security Trinity agent.
Coral joined data across 3 sources in a single SQL query.
""",
        severity=severity,  # 1=Low, 2=Medium, 3=High
        type="coral",
        source="SecurityTrinity",
        sourceRef=source_ref,
        tags=["coral", "cross-source", "auto-generated", github_user],
        tlp=2,  # Amber
        pap=2
    )
    
    response = thehive.create_alert(alert)
    
    if response.status_code == 201:
        alert_id = response.json()["id"]
        print(f"✅ Alert created: {alert_id}")
        return alert_id
    else:
        print(f"❌ Failed to create alert: {response.text}")
        return None

# ============================================
# FUNCTION 2: Add Observables to Alert
# ============================================

def add_observables_to_alert(alert_id, github_user, slack_channel):
    """Add observables (IPs, domains, etc.) to an alert"""
    
    observables = [
        {"dataType": "user", "data": github_user, "tlp": 2},
        {"dataType": "other", "data": slack_channel, "tlp": 2, "message": "Slack channel"},
        {"dataType": "text", "data": f"GitHub user {github_user} showed suspicious activity", "tlp": 2}
    ]
    
    for obs in observables:
        observable = CaseObservable(
            dataType=obs["dataType"],
            data=obs["data"],
            tlp=obs.get("tlp", 2),
            message=obs.get("message", "")
        )
        response = thehive.create_alert_observable(alert_id, observable)
        
        if response.status_code == 201:
            print(f"  📎 Added observable: {obs['dataType']}: {obs['data']}")
        else:
            print(f"  ❌ Failed to add {obs['dataType']}")

# ============================================
# FUNCTION 3: Promote Alert to Case
# ============================================

def promote_alert_to_case(alert_id):
    """Convert an alert into a full case for investigation"""
    
    response = thehive.promote_alert_to_case(alert_id)
    
    if response.status_code == 201:
        case_id = response.json()["id"]
        case_number = response.json()["caseId"]
        print(f"✅ Alert promoted to Case #{case_number} (ID: {case_id})")
        return case_id
    else:
        print(f"❌ Failed to promote alert: {response.text}")
        return None

# ============================================
# FUNCTION 4: Run Cortex Analyzer on Observable
# ============================================

def run_cortex_analyzer_on_case(case_id, analyzer_name="VirusTotal_GetReport"):
    """Run a Cortex analyzer on observables in a case"""
    
    # First, get the case observables
    response = thehive.get_case_observables(case_id)
    
    if response.status_code != 200:
        print(f"❌ Could not fetch observables")
        return
    
    observables = response.json()
    
    for obs in observables:
        data_type = obs.get("dataType")
        data = obs.get("data")
        
        if data_type == "user":  # Skip user data, not suitable for VirusTotal
            continue
            
        print(f"🔍 Running {analyzer_name} on {data_type}: {data}...")
        
        # Get Cortex analyzer ID
        analyzers = cortex.get_analyzers()
        
        # This requires Cortex API integration
        # See: https://github.com/TheHive-Project/Cortex4Py
        
        print(f"  Analyzer would run on {data}")

# ============================================
# FUNCTION 5: List All Existing Cases
# ============================================

def list_recent_cases(limit=5):
    """List recent cases from TheHive"""
    
    response = thehive.get_cases(limit=limit, sort="-createdAt")
    
    if response.status_code == 200:
        cases = response.json()
        print(f"\n📋 Recent Cases (last {len(cases)}):")
        for case in cases:
            print(f"  #{case.get('caseId')}: {case.get('title')} - {case.get('status')}")
        return cases
    else:
        print(f"❌ Failed to fetch cases: {response.text}")
        return []

# ============================================
# FUNCTION 6: Create Darwin Mutation in TheHive
# ============================================

def create_case_with_darwin_mutation(mutation_pattern, github_user, slack_channel):
    """Create a case documenting a Darwin-learned mutation"""
    
    source_ref = f"darwin-{uuid.uuid4().hex[:8]}"
    
    case = Case(
        title=f"[Darwin Learning] New Pattern Discovered: {mutation_pattern[:50]}",
        description=f"""
🧬 DARWIN EVOLUTION DETECTED

Pattern Learned: {mutation_pattern}

Source Data:
- GitHub User: {github_user}
- Slack Channel: {slack_channel}
- Timestamp: {datetime.now().isoformat()}

This mutation was automatically learned by the Darwin Loop during a Coral cross-source investigation.
The Security Trinity is now smarter.
""",
        severity=2,
        tags=["darwin", "mutation", "self-learning", "coral"],
        tlp=2,
        pap=2
    )
    
    response = thehive.create_case(case)
    
    if response.status_code == 201:
        case_id = response.json()["id"]
        print(f"🧬 Darwin Mutation Case Created: {case_id}")
        return case_id
    else:
        print(f"❌ Failed to create Darwin case: {response.text}")
        return None

# ============================================
# MAIN DEMO FUNCTION
# ============================================

def run_security_trinity_demo():
    """Full demonstration of Security Trinity integration"""
    
    print("\n" + "="*60)
    print("🏴‍☠️ SECURITY TRINITY - LIVE DEMO")
    print("="*60)
    
    # Demo data (from your actual Coral query results)
    demo_data = [
        {"github_user": "jrieken", "slack_channel": "social", "sentry_project": "javascript-nextjs", "contributions": 12778},
        {"github_user": "Tyriar", "slack_channel": "all-gosh1234", "sentry_project": "javascript-nextjs", "contributions": 12517},
    ]
    
    for data in demo_data:
        print(f"\n📡 Processing: {data['github_user']}")
        
        # Step 1: Create alert
        alert_id = create_alert_from_coral(
            data['github_user'], 
            data['slack_channel'], 
            data['sentry_project'],
            severity=2
        )
        
        if alert_id:
            # Step 2: Add observables
            add_observables_to_alert(alert_id, data['github_user'], data['slack_channel'])
            
            # Step 3: Promote to case
            case_id = promote_alert_to_case(alert_id)
            
            if case_id:
                # Step 4: Darwin learns - create mutation case
                mutation = f"GitHub user {data['github_user']} with {data['contributions']} contributions correlates with Slack channel {data['slack_channel']}"
                create_case_with_darwin_mutation(mutation, data['github_user'], data['slack_channel'])
    
    # Step 5: List all cases
    list_recent_cases(10)
    
    print("\n" + "="*60)
    print("✅ Security Trinity Demo Complete!")
    print("📊 Check TheHive UI at: http://localhost:9000")
    print("="*60)

# ============================================
# RUN THE DEMO
# ============================================

if __name__ == "__main__":
    run_security_trinity_demo()